name: Get new version for tag based on PR labels
description: Get new version for tag based on PR labels
inputs:
  pullRequestNumber:
    description: "Number of the pull request"
    required: false
  gitHubToken:
    description: "Token for the repo. will be github_token by default."
    required: false
  prefix:
    description: "Prefix of the tag"
    required: false

outputs:
  newversion:
    description: New version of the tag
    value: ${{ steps.getnewversion.outputs.newVersion }}

runs:
  using: "composite"
  steps:
    # - name: checkout
    #   uses: actions/checkout@v3
    #   with:
    #     path: ${{ runner.temp }}

    - name: get-new-version
      id: getnewversion
      shell: pwsh
      run: |
        $params = @{
          Prefix  = "${{ inputs.prefix }}"
        }
        if ("${{ inputs.pullRequestNumber }}") {
          $params.Add("PullRequestNumber", "${{ inputs.pullRequestNumber }}")
        }
        if ("${{ inputs.GitHubToken }}") {
          $params.Add("GitHubToken", "${{ inputs.gitHubToken }}")
        }

        ${{ github.action_path }}/scripts/Get-NewVersion.ps1 @params
      env:
        REPOSITORY: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
        GH_REF: ${{ github.ref }}
