name: "Get new version for tag based on SemVer"

inputs:
  pullRequestNumber:
    description: "Number of the pull request"
    required: false
  prefix:
    description: "Prefix of the tag"
    required: true

outputs:
  newversion:
    description: New version of the tag
    value: ${{ steps.getnewversion.outputs.newVersion }}

runs:
  using: "composite"
  steps:
    - name: get-new-version
      id: getnewversion
      shell: pwsh
      run: |
        $params = @{
          Prefix  = "${{ inputs.prefix }}"
        }
        if ("${{ inputs.pullRequestNumber }}") {
          $params.Add("PullRequestNumber", "${{ inputs.pullRequestNumber }}")
        }
        ./.github/scripts/Get-NewVersion.ps1 @params
      env:
        REPOSITORY: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
        GH_REF: ${{ github.ref }}
